# Generated by Django 4.1.5 on 2023-01-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Refbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("description", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RefbookVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("date", models.DateField()),
                (
                    "refbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.refbook"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefbookElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "refbook_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.refbookversion",
                    ),
                ),
            ],
        ),
    ]
