# Generated by Django 4.1.5 on 2023-01-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refbookelement",
            old_name="description",
            new_name="value",
        ),
    ]
